# Generated by Django 4.2.16 on 2025-02-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image_user_nom_user_phone_user_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departemets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('membre_eglise', models.PositiveBigIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_eglises/')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_responsables/')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénoms'),
        ),
        migrations.CreateModel(
            name='SousCategorieMateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='accounts.categoriemateriel')),
            ],
        ),
        migrations.CreateModel(
            name='Membres_logistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_membres_logisticiens')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('dprt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dprt', to='accounts.responsable', verbose_name='Département')),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_logistique', to='accounts.eglise')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('BON', 'Bon'), ('CRITIQUE', 'critique'), ('INUTILISABLE', 'Inutilisable')], default='BON', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.categoriemateriel')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='accounts.eglise')),
                ('sous_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.souscategoriemateriel')),
            ],
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eglise', to='accounts.responsable'),
        ),
        migrations.AddField(
            model_name='eglise',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eglise', to='accounts.ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='dprt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.departemets', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='user',
            name='eglise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='accounts.eglise'),
        ),
    ]
