# Generated by Django 4.2.16 on 2025-02-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_categoriemateriel_departemets_eglise_responsable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'Responsable église', 'verbose_name_plural': 'Responsables églises'},
        ),
        migrations.RemoveField(
            model_name='eglise',
            name='nom',
        ),
        migrations.AlterField(
            model_name='eglise',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_eglises/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='membre_eglise',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="Nombre de membre de l'église"),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eglise', to='accounts.responsable', verbose_name="Responsable de l'église"),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_logistique', to='accounts.eglise', verbose_name='Eglise'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_membres_logisticiens', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_responsables/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénoms'),
        ),
    ]
