# Generated by Django 4.2.16 on 2025-02-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_responsable_options_remove_eglise_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres_logistique',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_eglise', to='accounts.responsable'),
        ),
        migrations.AlterField(
            model_name='membres_logistique',
            name='dprt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dprt', to='accounts.departemets', verbose_name='Département'),
        ),
    ]
