# Generated by Django 4.2.16 on 2025-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membres_logistique_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materiels', verbose_name='Image'),
        ),
    ]
