# Generated by Django 4.2.16 on 2025-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_materiel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
